{
  "version": "3.8",
  "services": {
    "adguard-home": {
      "image": "adguard/adguardhome",
      "container_name": "adguard-home",
      "restart": "unless-stopped",
      "network_mode": "br0",
      "ports": [
        "3001:3000/tcp",
        "54:53/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/adguard_home/workingdir:/opt/adguardhome/work:rw",
        "/mnt/user/appdata/adguard_home/config:/opt/adguardhome/conf:rw"
      ]
    }
  }
}