{
  "version": "3.8",
  "services": {
    "ai-chat-app": {
      "image": "ghcr.io/imagegenius/ai-chat-app",
      "container_name": "ai-chat-app",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "NEXTAUTH_SECRET": "secret",
        "NEXTAUTH_URL": "http://192.168.1.2:3000",
        "ADMIN_EMAIL": "dldunning48@gmail.com",
        "ADMIN_PASSWORD": "twisted88",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "022"
      },
      "ports": [
        "3000:3000/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/ai-chat-app:/config:rw"
      ]
    }
  }
}