{
  "version": "3.8",
  "services": {
    "binhex-sabnzbd": {
      "image": "binhex/arch-sabnzbd",
      "container_name": "binhex-sabnzbd",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "8039:8080/tcp",
        "8038:8090/tcp"
      ],
      "volumes": [
        "/mnt/user/Downloads/:/data:rw",
        "/mnt/user/Downloads/:/config:rw"
      ]
    }
  }
}