{
  "version": "3.8",
  "services": {
    "binhex-radarr": {
      "image": "binhex/arch-radarr",
      "container_name": "binhex-radarr",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "7878:7878/tcp"
      ],
      "volumes": [
        "/mnt/user/Downloads/:/data:rw",
        "/mnt/user:/media:rw",
        "/mnt/user/appdata/binhex-radarr:/config:rw"
      ]
    }
  }
}