{
  "version": "3.8",
  "services": {
    "binhex-privoxyvpn": {
      "image": "binhex/arch-privoxyvpn",
      "container_name": "binhex-privoxyvpn",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "privileged": true,
      "environment": {
        "VPN_ENABLED": "yes",
        "VPN_USER": "vpn username",
        "VPN_PASS": "vpn password",
        "VPN_PROV": "pia",
        "VPN_CLIENT": "openvpn",
        "VPN_OPTIONS": "",
        "LAN_NETWORK": "192.168.1.0/24",
        "NAME_SERVERS": "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1",
        "SOCKS_USER": "admin",
        "SOCKS_PASS": "socks",
        "ENABLE_SOCKS": "no",
        "ENABLE_PRIVOXY": "yes",
        "VPN_INPUT_PORTS": "",
        "VPN_OUTPUT_PORTS": "",
        "DEBUG": "false",
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "8122:8118/tcp",
        "9118:9118/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/binhex-privoxyvpn:/config:rw"
      ]
    }
  }
}