{
  "version": "3.8",
  "services": {
    "binhex-jellyfin": {
      "image": "ghcr.io/binhex/arch-jellyfin",
      "container_name": "binhex-jellyfin",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "HEALTHCHECK_COMMAND": "",
        "HEALTHCHECK_ACTION": "",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "000"
      },
      "ports": [
        "8099:8096/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/binhex-jellyfin:/config:rw",
        "/mnt/user:/media:rw"
      ]
    }
  }
}