{
  "version": "3.8",
  "services": {
    "binhex-jenkins": {
      "image": "binhex/arch-jenkins",
      "container_name": "binhex-jenkins",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "privileged": true,
      "environment": {
        "JAVA_ARGS": "-Xmx512m",
        "JAVA_OPTS": "-Dhudson.footerURL=http://mycompany.com",
        "SHARED_NETWORK": "no",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "000"
      },
      "ports": [
        "8090:8090/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/binhex-jenkins:/config:rw"
      ]
    }
  }
}