{
  "version": "3.8",
  "services": {
    "binhex-nginx": {
      "image": "binhex/arch-nginx",
      "container_name": "binhex-nginx",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "8095:8080/tcp",
        "8443:8443/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/binhex-nginx:/config:rw"
      ]
    }
  }
}