{
  "version": "3.8",
  "services": {
    "binhex-qbittorrentvpn": {
      "image": "binhex/arch-qbittorrentvpn",
      "container_name": "binhex-qbittorrentvpn",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "privileged": true,
      "environment": {
        "VPN_ENABLED": "yes",
        "VPN_USER": "p9246235",
        "VPN_PASS": "85yoENr2JEPL",
        "VPN_PROV": "pia",
        "VPN_CLIENT": "openvpn",
        "VPN_OPTIONS": "",
        "STRICT_PORT_FORWARD": "yes",
        "ENABLE_PRIVOXY": "no",
        "WEBUI_PORT": "8080",
        "LAN_NETWORK": "192.168.1.0/24",
        "NAME_SERVERS": "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1",
        "VPN_INPUT_PORTS": "",
        "VPN_OUTPUT_PORTS": "",
        "DEBUG": "false",
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "6881:6881/tcp",
        "6881:6881/tcp",
        "8080:8080/tcp",
        "8118:8118/tcp"
      ],
      "volumes": [
        "/mnt/user/Downloads/:/data:rw",
        "/mnt/user/Downloads/:/data:rw",
        "/mnt/user/appdata/binhex-qbittorrentvpn:/config:rw"
      ]
    }
  }
}