{
  "version": "3.8",
  "services": {
    "binhex-prowlarr": {
      "image": "binhex/arch-prowlarr",
      "container_name": "binhex-prowlarr",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "9696:9696/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/binhex-prowlarr:/config:rw"
      ]
    }
  }
}