{
  "version": "3.8",
  "services": {
    "binhex-emby": {
      "image": "binhex/arch-emby",
      "container_name": "binhex-emby",
      "restart": "unless-stopped",
      "network_mode": "host",
      "environment": {
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100",
        "NVIDIA_VISIBLE_DEVICES": "all",
        "NVIDIA_DRIVER_CAPABILITIES": "all"
      },
      "ports": [
        "8096:8096/tcp"
      ],
      "volumes": [
        "/mnt/user:/media:rw",
        "/mnt/user/appdata/binhex-emby:/config:rw"
      ]
    }
  }
}