{
  "version": "3.8",
  "services": {
    "binhex-deluge": {
      "image": "binhex/arch-deluge",
      "container_name": "binhex-deluge",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "DELUGE_DAEMON_LOG_LEVEL": "info",
        "DELUGE_WEB_LOG_LEVEL": "info",
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "8080:8112/tcp",
        "58846:58846/tcp",
        "58946:58946/tcp",
        "58946:58946/tcp"
      ],
      "volumes": [
        "/mnt/user/Downloads/:/data:rw",
        "/mnt/user/appdata/binhex-deluge:/config:rw"
      ]
    }
  }
}