{
  "version": "3.8",
  "services": {
    "calibreweb": {
      "image": "technosoft2000/calibre-web",
      "container_name": "calibreweb",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "CONTAINER_TIMEZONE": "UTC",
        "PGID": "100",
        "PUID": "99",
        "SET_CONTAINER_TIMEZONE": "true"
      },
      "ports": [
        "8083:8083/tcp"
      ],
      "volumes": [
        "/mnt/user/Books/:/books:rw"
      ]
    }
  }
}