{
  "version": "3.8",
  "services": {
    "chromium": {
      "image": "lscr.io/linuxserver/chromium",
      "container_name": "chromium",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "CHROME_CLI": "https://www.linuxserver.io/",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "022"
      },
      "ports": [
        "3000:3000/tcp",
        "3001:3001/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/chromium:/config:rw"
      ]
    }
  }
}