{
  "version": "3.8",
  "services": {
    "creativeserver": {
      "image": "binhex/arch-minecraftbedrockserver",
      "container_name": "creativeserver",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "CREATE_BACKUP_HOURS": "12",
        "PURGE_BACKUP_DAYS": "14",
        "ENABLE_WEBUI_CONSOLE": "yes",
        "ENABLE_WEBUI_AUTH": "yes",
        "WEBUI_USER": "admin",
        "WEBUI_PASS": "",
        "WEBUI_CONSOLE_TITLE": "Minecraft Bedrock",
        "STARTUP_CMD": "",
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "ports": [
        "19134:19132/tcp",
        "19135:19132/tcp",
        "19136:19133/tcp",
        "19136:19133/tcp",
        "8223:8222/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/binhex-minecraftbedrockserver:/config:rw"
      ]
    }
  }
}