{
  "version": "3.8",
  "services": {
    "home-plex": {
      "image": "binhex/arch-plex",
      "container_name": "home-plex",
      "restart": "unless-stopped",
      "network_mode": "br0",
      "environment": {
        "TRANS_DIR": "/config/transcode",
        "NVIDIA_DRIVER_CAPABILITIES": "all",
        "NVIDIA_VISIBLE_DEVICES": "",
        "UMASK": "000",
        "PUID": "99",
        "PGID": "100"
      },
      "volumes": [
        "/mnt/user:/media:rw",
        "/mnt/user/appdata/home-plex:/config:rw"
      ]
    }
  }
}