{
  "version": "3.8",
  "services": {
    "kavita": {
      "image": "kizaing/kavita",
      "container_name": "kavita",
      "restart": "unless-stopped",
      "network_mode": "br0",
      "ports": [
        "5000:5000/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/kavita/:/kavita/config:rw",
        "/mnt/user/Books/:/library:rw",
        "/mnt/user/Books/:/Books:rw",
        "/mnt/user/Books Misc/:/Books Misc:rw"
      ]
    }
  }
}