{
  "version": "3.8",
  "services": {
    "openvpn-hyrosa": {
      "image": "testdasi/openvpn-hyrosa:latest",
      "container_name": "openvpn-hyrosa",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "DNS_SERVERS": "127.2.2.2",
        "HOST_NETWORK": "192.168.1.0/24",
        "SERVER_IP": "192.168.1.2",
        "LAUNCHER_GUI_PORT": "8000",
        "DNS_SERVER_PORT": "53",
        "SOCKS_PROXY_PORT": "9118",
        "HTTP_PROXY_PORT": "8118",
        "USENET_HTTP_PORT": "8080",
        "USENET_HTTPS_PORT": "8090",
        "TORRENT_GUI_PORT": "3000",
        "SEARCHER_GUI_PORT": "5076",
        "LANG": "en_GB.UTF-8"
      },
      "ports": [
        "8000:8000/tcp",
        "8153:53/tcp",
        "8153:53/tcp",
        "9118:9118/tcp",
        "8118:8118/tcp",
        "8085:8080/tcp",
        "8090:8090/tcp",
        "3000:3000/tcp",
        "5076:5076/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/openvpn-hyrosa:/root:rw",
        "/mnt/user/Downloads/:/data:rw"
      ]
    }
  }
}