{
  "version": "3.8",
  "services": {
    "plex-media-server": {
      "image": "plexinc/pms-docker",
      "container_name": "plex-media-server",
      "restart": "unless-stopped",
      "network_mode": "host",
      "environment": {
        "PLEX_CLAIM": "Insert Token from https://plex.tv/claim",
        "PLEX_UID": "99",
        "PLEX_GID": "100",
        "VERSION": "latest"
      },
      "volumes": [
        "/mnt/user/Transcode/:/transcode:rw",
        "/mnt/user/Media/:/data:rw",
        "/mnt/user/appdata/Plex-Media-Server:/config:rw"
      ]
    }
  }
}