{
  "version": "3.8",
  "services": {
    "plexmediaserver": {
      "image": "limetech/plex",
      "container_name": "plexmediaserver",
      "restart": "unless-stopped",
      "network_mode": "br0",
      "privileged": true,
      "volumes": [
        "/mnt/user/appdata/PlexMediaServer:/config:rw"
      ]
    }
  }
}