{
  "version": "3.8",
  "services": {
    "qbittorrent-vpn": {
      "image": "ghcr.io/hotio/qbittorrent:release",
      "container_name": "qbittorrent-vpn",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "VPN_ENABLED": "true",
        "VPN_LAN_NETWORK": "",
        "VPN_CONF": "wg0",
        "VPN_ADDITIONAL_PORTS": "",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "002"
      },
      "ports": [
        "8085:8080/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/qbittorrent-vpn:/config:rw"
      ]
    }
  }
}