{
  "version": "3.8",
  "services": {
    "qbittorrent": {
      "image": "ghcr.io/hotio/qbittorrent:release",
      "container_name": "qbittorrent",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "PUID": "99",
        "PGID": "100",
        "UMASK": "002"
      },
      "ports": [
        "8080:8080/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/qbittorrent:/config:rw"
      ]
    }
  }
}