{
  "version": "3.8",
  "services": {
    "qbittorrentvpn": {
      "image": "markusmcnugen/qbittorrentvpn",
      "container_name": "qbittorrentvpn",
      "restart": "unless-stopped",
      "network_mode": "br0",
      "privileged": true,
      "environment": {
        "WEBUI_PORT": "8080",
        "INCOMING_PORT": "8999",
        "VPN_ENABLED": "yes",
        "VPN_USERNAME": "p9246235",
        "VPN_PASSWORD": "85yoENr2JEPL",
        "LAN_NETWORK": "192.168.2.0/24",
        "NAME_SERVERS": "8.8.8.8,8.8.4.4",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "002"
      },
      "ports": [
        "8080:8080/tcp",
        "8999:8999/tcp",
        "8999:8999/tcp"
      ],
      "volumes": [
        "/mnt/user/Downloads/:/downloads:rw",
        "/mnt/user/appdata/qbittorrentvpn:/config:rw"
      ]
    }
  }
}