{
  "version": "3.8",
  "services": {
    "sillytavern": {
      "image": "ghcr.io/sillytavern/sillytavern:staging",
      "container_name": "sillytavern",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "ports": [
        "7598:8000/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/STConfig/Config:/home/node/app/config:rw",
        "/mnt/user/appdata/STConfig/Plugins:/plugins:rw",
        "/mnt/user/appdata/STConfig/Data:/home/node/app/data:rw"
      ]
    }
  }
}