{
  "version": "3.8",
  "services": {
    "tdarr_node": {
      "image": "ghcr.io/haveagitgat/tdarr_node",
      "container_name": "tdarr_node",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "serverIP": "192.168.1.223",
        "serverPort": "8266",
        "nodeIP": "0.0.0.0",
        "nodeID": "Node Name",
        "PUID": "99",
        "PGID": "100",
        "NVIDIA_VISIBLE_DEVICES": "all",
        "NVIDIA_DRIVER_CAPABILITIES": "all"
      },
      "ports": [
        "8267:8267/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/tdarr/configs:/app/configs:rw",
        "/mnt/user/appdata/tdarr/logs:/app/logs:rw",
        "/mnt/user/Media/:/mnt/media:rw",
        "/mnt/cache/Transcode/:/temp:rw"
      ]
    }
  }
}