{
  "version": "3.8",
  "services": {
    "tdarr": {
      "image": "ghcr.io/haveagitgat/tdarr",
      "container_name": "tdarr",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "serverIP": "0.0.0.0",
        "internalNode": "false",
        "nodeIP": "192.168.1.223",
        "nodeID": "MyInternalNode",
        "PUID": "99",
        "PGID": "100",
        "NVIDIA_VISIBLE_DEVICES": "all",
        "NVIDIA_DRIVER_CAPABILITIES": "all"
      },
      "ports": [
        "8266:8266/tcp",
        "8265:8265/tcp",
        "8264:8264/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/tdarr/server:/app/server:rw",
        "/mnt/user/appdata/tdarr/configs:/app/configs:rw",
        "/mnt/user/appdata/tdarr/logs:/app/logs:rw",
        "/mnt/user/Media/:/mnt/media:rw",
        "/mnt/cache/Transcode/:/temp:rw"
      ]
    }
  }
}