{
  "version": "3.8",
  "services": {
    "transmission_vpn": {
      "image": "haugene/transmission-openvpn:dev",
      "container_name": "transmission_vpn",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "privileged": true,
      "environment": {
        "OPENVPN_USERNAME": "p9246235",
        "OPENVPN_PASSWORD": "85yoENr2JEPL",
        "OPENVPN_CONFIG": "switzerland",
        "OPENVPN_PROVIDER": "PIA",
        "LOCAL_NETWORK": "192.168.0.0/24",
        "TRANSMISSION_RPC_USERNAME": "doug",
        "TRANSMISSION_RPC_PASSWORD": "twisted88",
        "OPENVPN_OPTS": "--inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings",
        "PUID": "99",
        "PGID": "100",
        "TRANSMISSION_DOWNLOAD_DIR": "/downloads",
        "TRANSMISSION_RPC_AUTHENTICATION_REQUIRED": "true",
        "TRANSMISSION_RATIO_LIMIT_ENABLED": "true",
        "TRANSMISSION_DOWNLOAD_QUEUE_SIZE": "15",
        "TRANSMISSION_CACHE_SIZE_MB": "10",
        "TRANSMISSION_INCOMPLETE_DIR": "/downloads/incomplete",
        "TRANSMISSION_WEB_UI": "transmission-web-control",
        "GLOBAL_APPLY_PERMISSIONS": "false",
        "WEBPROXY_ENABLED": "false",
        "PIA_OPENVPN_CONFIG_BUNDLE": "openvpn"
      },
      "ports": [
        "9091:9091/tcp"
      ],
      "volumes": [
        "/mnt/user/Downloads/:/data:rw",
        "/mnt/user/Downloads/:/downloads:rw",
        "/mnt/user/T_Media/Torrent/watch/:/watch:rw",
        "/mnt/user/Downloads/:/mnt/user/T_Media/Torrent/:rw"
      ]
    }
  }
}