{
  "version": "3.8",
  "services": {
    "ubooquity": {
      "image": "lscr.io/linuxserver/ubooquity",
      "container_name": "ubooquity",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "environment": {
        "MAXMEM": "maxmem",
        "PUID": "99",
        "PGID": "100",
        "UMASK": "022"
      },
      "ports": [
        "2202:2202/tcp",
        "2203:2203/tcp"
      ],
      "volumes": [
        "/mnt/user/Books/:/books:rw",
        "/mnt/user/Doug/Comics/:/comics:rw",
        "/mnt/user/Doug/Raw/:/files:rw",
        "/mnt/user/appdata/ubooquity:/config:rw"
      ]
    }
  }
}