{
  "version": "3.8",
  "services": {
    "ubuntu-playground": {
      "image": "ghcr.io/siwatinc/ubuntu-playground:latest",
      "container_name": "ubuntu-playground",
      "restart": "unless-stopped",
      "network_mode": "br0",
      "privileged": true,
      "environment": {
        "packages": "mc nano sudo"
      },
      "volumes": [
        "/mnt/user/appdata/ubuntudata:/home/root:rw"
      ]
    }
  }
}