{
  "version": "3.8",
  "services": {
    "wireguard-easy": {
      "image": "weejewel/wg-easy",
      "container_name": "wireguard-easy",
      "restart": "unless-stopped",
      "network_mode": "bridge",
      "privileged": true,
      "environment": {
        "WG_HOST": "161.97.166.25",
        "PASSWORD": "unraid"
      },
      "ports": [
        "51821:51821/tcp",
        "51820:51820/tcp"
      ],
      "volumes": [
        "/mnt/user/appdata/wireguard-easy:/etc/wireguard:rw"
      ]
    }
  }
}